blank_issues_enabled: false
contact_links:
  - name: Security Vulnerability Disclosure
    url: mailto:security@ambiware.ai
    about: Please report security issues privately.
  - name: Community Discussions
    url: https://github.com/loqalabs/loqa-meta/discussions
    about: Use discussions for questions and open-ended ideas.
